"""MN PKA Design-System Tokens — auto-generiert.

Aktualisiert manuell um v0.4.4-Tokens (S248) — beim naechsten Generator-Lauf
muessen die neuen Tokens in tokens/*.json mit aufgenommen werden, sonst werden
sie hier ueberschrieben. Generator liest typography.json + colors.json + spacing.json
(Stand v0.4.4 enthaelt alle neuen Keys).
"""

# Auto-generiert aus tokens/*.json via Style Dictionary.
# NICHT MANUELL BEARBEITEN — Aenderungen werden ueberschrieben.

TOKENS = {
    "color.indigo.50": "#eef2ff",
    "color.indigo.100": "#e0e7ff",
    "color.indigo.300": "#a5b4fc",
    "color.indigo.400": "#818cf8",
    "color.indigo.500": "#6366f1",
    "color.indigo.600": "#4F46E5",
    "color.indigo.700": "#4338ca",
    "color.indigo.900": "#312e81",
    "color.indigo.950": "#1e1b4b",
    "color.grey.50": "#f5f5f5",
    "color.grey.100": "#f3f4f6",
    "color.grey.150": "#eeeeee",
    "color.grey.200": "#e5e7eb",
    "color.grey.300": "#cbd5e1",
    "color.grey.400": "#9ca3af",
    "color.grey.500": "#6b7280",
    "color.grey.550": "#666666",
    "color.grey.600": "#999999",
    "color.grey.700": "#374151",
    "color.brand": "#C8102E",
    "color.status.success": "#2e7d32",
    "color.status.warning": "#f59e0b",
    "color.status.urgent": "#e65100",
    "color.status.error": "#D32F2F",
    "color.status.error-bg": "#ffebee",
    "color.status.warning-bg": "#fff3e0",
    "color.status.error-tint": "#fff8f7",
    "color.status.warning-tint": "#fffaf5",
    "color.status.info-tint": "#f5f8ff",
    "color.accent.warm.strong": "#d97706",
    "color.accent.warm.soft": "#fef3c7",
    "color.accent.warm.text": "#78350f",
    # S248: Severity-Skala (Variante F nach DS-Decisions v03 §2)
    "color.severity.high": "#dc2626",
    "color.severity.medium": "#a16207",
    "color.severity.low": "#6b7280",
    "color.severity.high-bg": "#fee2e2",
    "color.severity.medium-bg": "#fef3c7",
    "color.severity.low-bg": "#f3f4f6",
    "color.viz.muted": "#b0bec5",
    "color.viz.success-soft": "#90caf9",
    "color.viz.neutral-soft": "#e0e0e0",
    "color.viz.dark-navy": "#1a237e",
    "color.viz.medium-blue": "#283593",
    "color.light.bg": "#fdfdfd",
    "color.light.surface": "#ffffff",
    "color.light.surface-subtle": "#f6f6f6",
    "color.light.surface-elev": "#f6f6f6",
    "color.light.border": "#cbd5e1",
    "color.light.border-subtle": "#e5e7eb",
    "color.light.text": "#1e1b4b",
    "color.light.text-muted": "#6b7280",
    "color.light.text-subtle": "#9ca3af",
    "color.light.h1": "#312e81",
    "color.light.h2": "#4338ca",
    "color.light.accent": "#4F46E5",
    "color.light.accent-soft": "#e0e7ff",
    "color.dark.bg": "#0a0a0d",
    "color.dark.surface": "#14141a",
    "color.dark.surface-subtle": "#1a1a22",
    "color.dark.surface-elev": "#1f1f29",
    "color.dark.border": "#2d2d38",
    "color.dark.border-subtle": "#1f1f29",
    "color.dark.text": "#f5f5f7",
    "color.dark.text-muted": "#888894",
    "color.dark.text-subtle": "#555560",
    "color.dark.h1": "#f5f5f7",
    "color.dark.h2": "#a5b4fc",
    "color.dark.accent": "#818cf8",
    "color.dark.accent-soft": "rgba(99,102,241,0.16)",
    "radius.none": "0",
    "radius.subtle": "2px",
    "radius.card": "4px",
    "radius.input": "4px",
    "radius.round": "9999px",
    "space.1": "4px",
    "space.2": "8px",
    "space.3": "12px",
    "space.4": "16px",
    "space.5": "20px",
    "space.6": "24px",
    "space.8": "32px",
    "space.10": "40px",
    "space.12": "48px",
    "space.16": "64px",
    "space.20": "80px",
    # S248: Semantische Aliase fuer kontextabhaengiges Spacing (KT-1-Klassen)
    "space.semantic.tight-min": "4px",
    "space.semantic.tight": "8px",
    "space.semantic.default": "12px",
    "space.semantic.wide": "20px",
    "space.semantic.wide-max": "32px",
    "space.semantic.section": "48px",
    # S248: Indent-Tokens (heute hardcoded leftIndent=3*mm)
    "space.indent.bullet": "12px",
    "space.indent.subitem": "24px",
    "space.indent.code": "16px",
    # S248 v0.5.0: zusaetzliche semantische Tokens (waren hardcoded)
    "space.semantic.sub-tight":      "2px",   # 0.5mm — Anriss-Bullet-spaceAfter
    "space.semantic.bibel-quelle":   "7px",   # 1.8mm — BibelQuelle-spaceBefore
    "space.semantic.tracker-item":   "6px",   # 1.5mm — Tracker-Item-spaceAfter
    "space.semantic.divider":        "16px",  # 4mm — section_divider() Spacing
    "space.semantic.between-modules":"24px",  # 6mm — Spacing zwischen Modul-Bloecken
    # S248 v0.5.0: Logo-Tokens (waren hardcoded LOGO_SIZE=18mm, LOGO_GAP=4mm)
    "space.logo.size":           "18mm",
    "space.logo.gap":            "4mm",
    "space.logo.size-small":     "14mm",
    "space.page.margin-top": "22mm",
    "space.page.margin-bottom": "22mm",
    "space.page.margin-inner": "22mm",
    "space.page.margin-outer": "18mm",
    "space.page.col-gutter": "8mm",
    "stack.active": "A",
    "stack.available.A": "Geist + Source Serif 4 Italic",
    "stack.available.D": "Source Sans 3 nativ",
    "stack.size_factor.A": "1.0",
    "stack.size_factor.D": "1.10",
    "stroke.hairline": "0.4pt",
    "stroke.thin": "0.5pt",
    "stroke.default": "1pt",
    "stroke.thick": "1.5pt",
    "stroke.heavy": "2pt",
    "shadow.none": "none",
    "shadow.subtle": "0 1px 2px rgba(0,0,0,0.05)",
    "shadow.card": "0 4px 16px rgba(0,0,0,0.08)",
    "shadow.modal": "0 10px 40px rgba(0,0,0,0.12)",
    "font.family.sans": "Geist",
    "font.family.italic-editorial": "SourceSerif4-Italic",
    "font.family.italic-ui": "Geist-Medium",
    "font.family.mono": "JetBrainsMono",
    "font.family.math": "STIXTwoMath",
    "font.family.icon": "Phosphor",
    "font.size.h0": "26pt",
    "font.size.h1": "24pt",
    "font.size.h2": "15pt",
    "font.size.h3": "13pt",
    "font.size.body": "9.5pt",
    "font.size.lead": "11pt",
    "font.size.caption": "9pt",
    "font.size.code": "9pt",
    "font.size.bibel": "12pt",
    "font.size.math": "12pt",
    # S248 KT-1: neue Use-Case-Tokens (Footer-Familie, Page-Title, Icons)
    "font.size.title-page": "22pt",
    "font.size.footer-page": "8pt",
    "font.size.disclaimer": "8pt",
    "font.size.source": "8pt",
    "font.size.icon-large": "22pt",
    "font.size.icon-medium": "14pt",
    "font.size.icon-small": "11pt",
    # S248 v0.5.0: Section-Title (war hardcoded fontSize=18 in pdf_utils title-Style)
    "font.size.title-section": "18pt",
    # S248 v0.5.0: News-Headline (Item-Title, fett, ueber Body)
    "font.size.news-headline":      "11pt",
    # News-Body bleibt = font.size.body (9.5pt), keine length-spezifischen Tokens.
    # Length-Steuerung erfolgt ueber Wort-Limit im ETL-Layer, nicht ueber Schrift.
    "font.leading.h0": "31pt",
    "font.leading.h1": "28pt",
    "font.leading.h2": "19pt",
    "font.leading.h3": "17pt",
    "font.leading.body": "13.5pt",
    "font.leading.lead": "17pt",
    "font.leading.caption": "12pt",
    "font.leading.code": "13pt",
    "font.leading.bibel": "17pt",
    "font.leading.math": "16pt",
    # S248: Leadings fuer neue Use-Case-Tokens
    "font.leading.title-page": "26pt",
    "font.leading.footer-page": "10pt",
    "font.leading.disclaimer": "10pt",
    "font.leading.source": "10pt",
    "font.leading.icon-large": "26pt",
    "font.leading.icon-medium": "18pt",
    "font.leading.icon-small": "13pt",
    # S248 v0.5.0: Leadings fuer neue Tokens
    "font.leading.title-section":   "22pt",
    "font.leading.news-headline":   "14pt",
    # S248: Greek-Letters Fallback-Font (Sigma-Glyph-Bug Briefing/PDF V3)
    "font.family.fallback-greek": "STIXTwoText",
    # S248: Tabellen-Schrift-Token (Default = sans, Datentabellen koennen mono nutzen)
    "font.family.table-default": "Geist",
    "font.family.table-data": "JetBrainsMono",
    "font.weight.light": "300",
    "font.weight.regular": "400",
    "font.weight.medium": "500",
    "font.weight.bold": "700",
    "font.tracking.tight": "-0.02em",
    "font.tracking.normal": "0",
    "font.tracking.wide": "0.04em",
    "font.tracking.extra": "0.18em",
    "font.hyphenation.enabled": True,
    "font.hyphenation.lang": "de_DE",
    "font.hyphenation.min-word-length": 6,
    "font.hyphenation.min-chars-before": 3,
    "font.hyphenation.min-chars-after": 3,
}

# Helper
def get(key, default=None):
    """Token-Lookup mit Default. Beispiel: get("color.light.text")."""
    return TOKENS.get(key, default)
